source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
use_frameworks!

target 'YourCoin' do
	pod 'AlamofireObjectMapper', '~> 5.0'
	pod 'ObjectMapper', '~> 3.1'
	pod 'BigInt', '~> 3.0'
  	pod 'R.swift'
  	pod 'JSONRPCKit', :git=> 'https://github.com/bricklife/JSONRPCKit.git'
  	pod 'APIKit'
  	pod 'Geth'
	pod 'RxSwift',    '~> 4.0'
    	pod 'RxCocoa',    '~> 4.0'
  	pod 'EAIntroView'
  	pod 'Eureka', '~> 4.0.1'
  	pod 'MBProgressHUD'
  	pod 'StatefulViewController'
  	pod 'QRCodeReaderViewController', :git=>'https://github.com/yannickl/QRCodeReaderViewController.git', :branch=>'master'
  	pod 'KeychainSwift'
  	pod 'SwiftLint'
  	pod 'SeedStackViewController'
  	pod 'RealmSwift'
	pod 'JTMaterialSpinner', '~> 2.0'
  	pod 'BonMot', '~> 5.0'
  	pod 'VENTouchLock'
  	pod '1PasswordExtension'
  	pod 'Lokalise'
  	pod 'Moya', '~> 10.0.1'
  	pod 'JavaScriptKit' 
  	pod 'CryptoSwift', :git=>'https://github.com/krzyzanowskim/CryptoSwift', :branch=>'master'
end